### ISSUE TITLE
requestMicrophoneOpen always returns with "permission-denied"

### ISSUE THREAD

**Issue by develephant** [alexa-samples/skill-sample-nodejs-web-api-hello-world#1]
Hello.

First, thank you very much for this excellent example. I have run into one issue though and I am hoping you can enlighten me as to what it might be.

When using the following code, the response is always "permission-denied" so I was curious if there is a setting in the skill that I need to add for the microphone permission?

No other microphone access is taking place at the time of testing.

```js
    printDebug('requesting the microphone open');
    alexaClient.voice.requestMicrophoneOpen({
        onOpened: () => printDebug('the microphone was opened'),
        onClosed: () => printDebug('the microphone was closed'),
        onError: (err) => {
            printDebug('failed to open the microphone:');
            printDebug(err);
        }
    })
```

Thanks in advance.

**Comment by amzabhipats** [comment]
@develephant : Glad you found the repo useful. There are some limitations/restrictions on the usage of `requestMicrophoneOpen()` i.e. there are circumstances in which this may not work on device, and will change over time.
You'll need to implement a fallback to round trip to the skill via `alexaClient.skill.sendMessage ` to ensure the mic opens regardless.
I'll update the repo to reflect this.

**Comment by develephant** [comment]
Thank you. I appreciate the response.
