### ISSUE TITLE
Error to initialize client

### ISSUE THREAD

**Issue by guilhermelirio** [alexa-samples/skill-sample-nodejs-web-api-hello-world#2]
Good afternoon. I've always used the web api for games for some prototypes, and yesterday when I started developing a game, I came across an error:

![image](https://github.com/alexa-samples/skill-sample-nodejs-web-api-hello-world/assets/23419633/12a452ed-62ee-4f68-9363-a55f958d383c)
![image](https://github.com/alexa-samples/skill-sample-nodejs-web-api-hello-world/assets/23419633/58b81179-6270-4ec8-8a44-9fe84717831c)

https://appassets.androidplatform.net/?d=%7B%22action%22%3A%22alexa-html-initialize%22%2C%22data%22%3A%7B%7D%7D

This URL appearing inside https://cdn.html.games.alexa.a2z.com/alexa-html/latest/alexa-html.js appears to be offline.

Does anyone know how to resolve?

**Comment by guilhermelirio** [comment]
Nobody?

I want to develop a game for Alexa, but it's complicated.

**Comment by mhaddy** [comment]
@guilhermelirio Prototype your game locally as you have been doing, and then to test the Alexa integration, deploy your web app and test on device. The URL referenced therein only loads on device.

**Comment by amzabhipats** [comment]
@guilhermelirio : The CDN url is fine. You can verify this by loading the URL in the browser directly. The issue (as pointed out by mhaddy) seems to be the cause as you won't be able to create the `Alexa` object when running locally (i.e. that object will only get instantiated properly when run on device). You can verify this by setting a breakpoint on Line 30 in  [web/index.js](https://github.com/alexa-samples/skill-sample-nodejs-web-api-hello-world/blob/main/web/index.js).
Hope this helps.
